// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDialogs.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClientDialogModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientDialogModel class.
        /// </summary>
        public ClientDialogModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientDialogModel class.
        /// </summary>
        /// <param name="type">Possible values include: 'Info', 'Warning',
        /// 'Question'</param>
        public ClientDialogModel(DialogType type, string id = default(string), string clientId = default(string), string header = default(string), string text = default(string), IList<DialogActionModel> actions = default(IList<DialogActionModel>))
        {
            Id = id;
            Type = type;
            ClientId = clientId;
            Header = header;
            Text = text;
            Actions = actions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Info', 'Warning', 'Question'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public DialogType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Header")]
        public string Header { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Actions")]
        public IList<DialogActionModel> Actions { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Actions != null)
            {
                foreach (var element in Actions)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
