// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDialogs.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DialogActionModel
    {
        /// <summary>
        /// Initializes a new instance of the DialogActionModel class.
        /// </summary>
        public DialogActionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DialogActionModel class.
        /// </summary>
        /// <param name="type">Possible values include: 'Submit',
        /// 'Checkbox'</param>
        public DialogActionModel(ActionType type, string id = default(string), string text = default(string))
        {
            Id = id;
            Type = type;
            Text = text;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Submit', 'Checkbox'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public ActionType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
