// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDialogs.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubmitDialogRequest
    {
        /// <summary>
        /// Initializes a new instance of the SubmitDialogRequest class.
        /// </summary>
        public SubmitDialogRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubmitDialogRequest class.
        /// </summary>
        public SubmitDialogRequest(string clientId = default(string), string dialogId = default(string), string actionId = default(string))
        {
            ClientId = clientId;
            DialogId = dialogId;
            ActionId = actionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DialogId")]
        public string DialogId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActionId")]
        public string ActionId { get; set; }

    }
}
