// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDialogs.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubmittedDialogResult
    {
        /// <summary>
        /// Initializes a new instance of the SubmittedDialogResult class.
        /// </summary>
        public SubmittedDialogResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubmittedDialogResult class.
        /// </summary>
        public SubmittedDialogResult(bool submitted)
        {
            Submitted = submitted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Submitted")]
        public bool Submitted { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
